#To deploy my code on my self hosted runner

name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - advanced

  jobs:
   deploy:
    runs-on: self-hosted

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Docker login
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Deploy docker container with docker compose
      run: |
      docker compose pull
      docker compose up -d