#Goal - to build and push devboard frontend image of master branch.
name: ci

on:
    push:
      branches:  [master]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check username
        run: echo "Username: ${{ vars.DOCKER_USERNAME }}"

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v7
        with: 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devboard-fe-master:latest
    
