# Linting Go language code with multiple versions:

name: Matrix

on:
  workflow_dispatch:

jobs:
  Linting:
    strategy:
      fail-fast: true # isse agr ek version se fail hogya to job nhi rukegi
      matrix:
        go-versions: ['1.22', '1.23', '1.24']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Conde
        uses: actions/Checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{matrix.go-versions}}
          #go-version-file: 'go.mod'
          cache: true

      - name: Go Formatter
        run: go fmt
        working-directory: backend

      - name: Go Vet
        run: go vet
        working-directory: backend